name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit authors
        env:
          COMMIT_AUTHORS: ${{ toJson(github.event.commits.*.author) }}
        run: echo "$COMMIT_AUTHORS"
      - name: commit author names
        env:
          COMMIT_AUTHOR_NAMES: ${{ toJson(github.event.commits.*.author.name) }}
        run: echo "$COMMIT_AUTHOR_NAMES"
